name: build-website

on:
  push:
    branches:
      - main

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Extract frontend properties
        id: frontend-properties
        uses: rexdefuror/read-package-json@v1.0.5

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Generate release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "v${{ env.PACKAGE_VERSION }}"
          prerelease: false
          title: "Release v${{ env.PACKAGE_VERSION }}"
          files: |
            dist/**
